<!DOCTYPE ichicsr  [
 

<!-- PUBLIC "-//ICHM2//DTD ICH ICSR Vers. 2.1//EN"  "ich-icsr-v2.1.dtd"  -->



<!--

  Individual Case Safety Report Document Type Definition



  This DTD is issued by the ICH M2 group and is public domain in

  nature.



	  No one can claim copyright on this DTD.

	  No commercial distribution is allowed.



The ICH is not responsible for any damage or financial loss resulting from use of this DTD. This version is tentative in nature and changes are expected. This DTD is subject to the ICH M2 change control procedures.

  Version 1.0, Release 1.0, October 17, 1997

   

1998-04-21 Modifications made by JPMA



1. Changed "resultstestsprocedures" to "resultstestsprocedures?".

			

2. Spelling correction "seriousnesslifethreatning" to "seriousnesslifethreatening".



3. Spelling correction "seriousnessconginitalanomali" to "seriousnesscongenitalanomali".



4. Changed ELEMENT "parentmedicalstructure" to "parentmedicalepisodename".

   

1998-09-27 Modifications made by FDA 



5. Added lang attribute to ichicsr as #REQUIRED using a %lang.att entity.



6. Added lang attribute to all other elements as #IMPLIED. 



7. Removed all unordered "&" connectors and replaced with the ordered connector "," to be compatible with XML.



8. Changed the names of elements under "ichicsrmessageheader" to comply with group decisions.



9. Removed all "old" elements.



10. Removed all sequence number entities.



11. Added Standard SGML character entities &lt;, &gt;, &amp; so that markup can be escaped as necessary.



12. Removed the %act.rec; and %ope.rec; internal entities, thus removing all support for the "(app | rep | del )" construct.



13. Root element of DTD is now "ichicsr" which allows one "ichicsrmessageheader" followed by "safetyreport+".



14. The relationship between "drug" and "activesubstance" is now one to zero or many.



Version 2.0, Release 1.0, Date to be decided



Version 2.1, Release 1.0, agreed November 2000

Documentation of changes made in version 2.0 to version 2.1 should be completed for implementation.

Safety Report Version (ICH ICSR M2 Data Processing element) is not an E2BM data element, but rather 

should be used for technical transmission purposes.  

Date of final release of Version 2.1 February 1, 2001



After San Diego ICH 5, this DTD was fixed to be final version for Version 2.1.

Version 2.1, Release 2.0, agreed Feburary 2001.





-->



<!-- TECHNICAL NOTE



			ICH ICSR SGML Declaration



To correctly parse an ICH ICSR SGML message requires the selection of the correct SGML declaration, along with this DTD, and the ICH ICSR SGML instance.  This technical note provides guidance on which of several SGML declarations included with the ICH ICSR application to select based on the language and character set used within the ICH ICSR SGML instance.  The method by which an SGML parser is told to use a specific declaration is parser specific.

The three most common methods are -



1. Tell the parser via the command line which declaration to use.



2. Tell the parser via a specific environment variable which declaration to use.



3. If the parser supports SGML Open catalogs, within the catalog file is a command that can tell the parser which declaration to use.  SGML catalog files are an industry standard way to tell a parser how to find all of the pieces (declaration, DTD, SGML document instance) needed to successfully parse.



To cover all of the languages necessary to support the ICH ICSR application,ISO 10646 (UNICODE) would have to be used.  If this were the case, then only one SGML declaration would be needed to support all ICH ICSR languages. Because UNICODE support is not available in all popular computer application programs, the ICH M2 EWG has recommended that a variety of character sets be used at this time, instead of a single UNICODE character encoding.  For each of these different character encodings a different SGML declaration needs to be generated and used.      



Five SGML declarations are included with the ICH ICSR distribution.  They are described briefly below.



ich-icsr-latin1.dcl - This SGML declaration supports the ISO 8859-1 (Latin 1) character set.  This character set supports English, and most Western European languages.



ich-icsr-latin7.dcl - This SGML declaration supports the ISO 8859-7 (Latin 7) character set.  This character set supports Greek. 



ich-icsr-sjis.dcl - This SGML declaration supports the Shift JIS character set for encoding Japanese.



ich-icsr-utf8.dcl - This SGML declaration supports the ISO 10646 (UNICODE) UTF-8 character set.  This character set supports almost all of the world's currently written languages.



ich-icsr-mult.dcl - This SGML declaration will support all of the currently defined ICHICSR languages, and it doesn't require the use of UNICODE.  It is however a "hack" that relies on a fortuitous characteristic of the languages currently being used within the ICH ICSR SGML application.  



This hack works because the character set documented within an SGML declaration is for the benefit of both the SGML parser and the programmer who implements the SGML application.  The programmer needs detailed knowledge of all the characters being used to correctly code an application.  The parser only really needs to know about some of the characters.  In particular it needs to know which characters signify an SGML event.  For instance that the "<" character starts an SGML open tag, and the "</" character sequence starts an SGML close tag.  All told, the parser needs to know very little.  Because of the particular combination of character sets being used within the ICH ICSR application, an SGML declaration can be defined that tells the parser just what it needs to know and still work across all of the different  character sets.  The catch is that this SGML declaration doesn't tell the programmer all that she or he needs to know to correctly code the rest of the application.  If this declaration is used, the programmer will have to get this detailed information from another source.



-->

                          

<!-- ================================================================== -->

<!-- Entities                                                           -->

<!-- ================================================================== -->



<!-- Use the lang attribute to indicate the language of an elements          content via an ISO 639 language Code.                              -->

 

<!ENTITY % lang.att "lang CDATA #IMPLIED">



<!-- Standard Character Entities to escape SGML special characters.     

  When "<", ">", and "&" occur in text, they should be replaced      

   by "&lt;", "&gt;", and "&amp;" respectively.                       -->



<!-- Less Than "<" -->

<!ENTITY lt     "&#38;#60;">



<!-- Greater Than ">" -->

<!ENTITY gt     "&#62;"> 



<!-- Ampersand "&" -->

<!ENTITY amp    "&#38;#38;"> 



<!-- ================================================================== -->

<!-- Elements and Attributes                                            -->

<!-- ================================================================== -->



<!ELEMENT ichicsr               	(ichicsrmessageheader, safetyreport+)>

<!ATTLIST ichicsr

	lang	CDATA	#REQUIRED

>



<!-- M.1 ICH ICSR Message Header Information -->



<!ELEMENT ichicsrmessageheader         	

	(messagetype			,

	messageformatversion		, 

	messageformatrelease		,

	messagenumb			,

	messagesenderidentifier         ,

	messagereceiveridentifier	,

        messagedateformat               ,

	messagedate)>

<!ATTLIST ichicsrmessageheader 	lang CDATA #IMPLIED

>



<!-- M.1.1 Message Type -->

<!ELEMENT messagetype		 (#PCDATA) >

<!ATTLIST messagetype

	lang CDATA #IMPLIED

>



<!-- M.1.2 Message Format Version -->

<!ELEMENT messageformatversion 	 (#PCDATA) >

<!ATTLIST messageformatversion

	lang CDATA #IMPLIED

>



<!-- M.1.3 Message Format Release -->

<!ELEMENT messageformatrelease 	 (#PCDATA) >

<!ATTLIST messageformatrelease

	lang CDATA #IMPLIED

>



<!-- M.1.4 Message Number -->

<!ELEMENT messagenumb	 	 (#PCDATA) >

<!ATTLIST messagenumb

	lang CDATA #IMPLIED

>



<!-- M.1.5 Message Sender Identifier -->

<!ELEMENT messagesenderidentifier  (#PCDATA) >		

<!ATTLIST messagesenderidentifier

	lang CDATA #IMPLIED

>



<!-- M.1.6 Message Receiver Identifier -->

<!ELEMENT messagereceiveridentifier  (#PCDATA) >

<!ATTLIST messagereceiveridentifier

	lang CDATA #IMPLIED

>



<!-- M.1.7a Message Date Format -->

<!ELEMENT messagedateformat          (#PCDATA)>

<!ATTLIST messagedateformat

        lang CDATA #IMPLIED

>



<!-- M.1.7b Message Date -->

<!ELEMENT messagedate		(#PCDATA) >

<!ATTLIST messagedate

	lang CDATA #IMPLIED

>



<!-- Individual Case Safety Report(s) Specifications -->

<!-- A.1 Identification of the case safety report   -->



<!ELEMENT safetyreport		     

        (safetyreportversion?,

        safetyreportid			,

	primarysourcecountry?		,

	occurcountry?                   ,

        transmissiondateformat?         ,

	transmissiondate?               ,

	reporttype?                     ,

	serious?                        ,

	seriousnessdeath?               ,

	seriousnesslifethreatening?     ,

	seriousnesshospitalization?     ,

	seriousnessdisabling?           ,

	seriousnesscongenitalanomali?   ,

	seriousnessother?               ,

        receivedateformat?              ,

	receivedate?                    ,

        receiptdateformat               ,

	receiptdate                     ,

	additionaldocument?             ,

	documentlist?                   ,

	fulfillexpeditecriteria?        ,

	authoritynumb?                  ,

	companynumb?                    ,

	duplicate?                     	,

	casenullification?              ,

	nullificationreason?            ,

	medicallyconfirm?               ,

		(reportduplicate*               ,

		linkedreport*                   ,

		primarysource+                  ,

		sender                          ,

		receiver                        ,

		patient))>

<!ATTLIST safetyreport

        lang CDATA #IMPLIED

>



<!ELEMENT reportduplicate	

        (duplicatesource?		,

	duplicatenumb?)>

<!ATTLIST reportduplicate

	lang CDATA #IMPLIED

>



<!ELEMENT linkedreport		     (linkreportnumb?)>

<!ATTLIST linkedreport

	lang CDATA #IMPLIED

>



<!-- A.2 Primary source(s) of information -->

<!ELEMENT primarysource		

        (reportertitle?                 ,

	reportergivename?               ,

	reportermiddlename?             ,

	reporterfamilyname?             ,

	reporterorganization?           ,

	reporterdepartment?             ,

	reporterstreet?                 ,

	reportercity?                   ,

	reporterstate?                  ,

	reporterpostcode?               ,

	reportercountry?                ,

	qualification?                  ,

	literaturereference?            ,

	studyname?                      ,

	sponsorstudynumb?               ,

	observestudytype?)>

<!ATTLIST primarysource

	lang CDATA #IMPLIED

>



<!-- A.3.1 Sender -->

<!ELEMENT sender                

	(sendertype?                    ,

	senderorganization              ,

	senderdepartment?               ,

	sendertitle?                    ,

	sendergivename?                 ,

	sendermiddlename?               ,

	senderfamilyname?               ,

	senderstreetaddress?            ,

	sendercity?                     ,

	senderstate?                    ,

	senderpostcode?                 ,

	sendercountrycode?              ,

	sendertel?                      ,

	sendertelextension?             ,

	sendertelcountrycode?           ,

	senderfax?                      ,

	senderfaxextension?             ,

	senderfaxcountrycode?           ,

	senderemailaddress?)>

<!ATTLIST sender

	lang CDATA #IMPLIED

>



<!-- A.3.2 Receiver -->

<!ELEMENT receiver              

	(receivertype?                  ,

	receiverorganization?           ,

	receiverdepartment?             ,

	receivertitle?                  ,

	receivergivename?               ,

	receivermiddlename?             ,

	receiverfamilyname?             ,

	receiverstreetaddress?          ,

	receivercity?                   ,

	receiverstate?                  ,

	receiverpostcode?               ,

	receivercountrycode?            ,

	receivertel?                    ,

	receivertelextension?           ,

	receivertelcountrycode?         ,

	receiverfax?                    ,

	receiverfaxextension?           ,

	receiverfaxcountrycode?         ,

	receiveremailaddress?)>

<!ATTLIST receiver

	lang CDATA #IMPLIED

>



<!-- B.1 Patient characteristics -->

<!ELEMENT patient               

	(patientinitial?                ,

	patientgpmedicalrecordnumb?     ,

	patientspecialistrecordnumb?    ,

	patienthospitalrecordnumb?      ,

	patientinvestigationnumb?       ,

        patientbirthdateformat?         ,

	patientbirthdate?               ,

	patientonsetage?                ,

        patientonsetageunit?            ,

	gestationperiod?                ,

        gestationperiodunit?            ,

	patientagegroup?                ,

	patientweight?                  ,

	patientheight?                  ,

	patientsex?                     ,

        lastmenstrualdateformat?	,

	patientlastmenstrualdate?       ,

	patientmedicalhistorytext?      ,

	resultstestsprocedures?         ,

		(medicalhistoryepisode*         ,

		patientpastdrugtherapy*         ,

		patientdeath?                   ,

		parent?                         ,

		reaction+                       ,

		test*                           ,

		drug+                           ,

		summary?))>

<!ATTLIST patient

	lang CDATA #IMPLIED

>



<!-- B.1.7 Relevant medical history and concurrent -->

<!ELEMENT medicalhistoryepisode 

        (patientepisodenamemeddraversion?,

        patientepisodename?		 ,

        patientmedicalstartdateformat?   ,

	patientmedicalstartdate?         ,

	patientmedicalcontinue?          ,

        patientmedicalenddateformat?     ,

	patientmedicalenddate?           ,

	patientmedicalcomment?)>

<!ATTLIST medicalhistoryepisode

	lang CDATA #IMPLIED

>



<!-- B.1.8 Relevant past drug history -->

<!ELEMENT patientpastdrugtherapy	

        (patientdrugname?               ,

        patientdrugstartdateformat?     ,

	patientdrugstartdate?           ,

        patientdrugenddateformat?       ,

	patientdrugenddate?             ,

	patientindicationmeddraversion?	,

	patientdrugindication?          ,

	patientdrgreactionmeddraversion?,

	patientdrugreaction?)>



<!ATTLIST patientpastdrugtherapy

	lang CDATA #IMPLIED

>



<!-- B.1.9 In case of death: -->

<!ELEMENT patientdeath		

        (patientdeathdateformat?        ,

	patientdeathdate?		,

	patientautopsyyesno?		,

		(patientdeathcause*	,

		patientautopsy*)) >

<!ATTLIST patientdeath

	lang CDATA #IMPLIED

>





<!ELEMENT patientdeathcause	

	(patientdeathreportmeddraversion?,

        patientdeathreport?)>

<!ATTLIST patientdeathcause

	lang CDATA #IMPLIED

>



<!ELEMENT patientautopsy	        

	 (patientdetermautopsmeddraversion?,

         patientdetermineautopsy?)>

<!ATTLIST patientautopsy

	lang CDATA #IMPLIED

>



<!-- B.1.10 For a parent-child / fetus report, information concerning the parent: -->

<!ELEMENT parent                

	(parentidentification?          ,

        parentbirthdateformat?          ,

	parentbirthdate?                ,

	parentage?                      ,

        parentageunit?                  ,

        parentlastmenstrualdateformat?  ,

	parentlastmenstrualdate?	,

	parentweight?                   ,

	parentheight?                   ,

	parentsex?                      ,

	parentmedicalrelevanttext?      ,

		(parentmedicalhistoryepisode*   ,

		parentpastdrugtherapy*))>

<!ATTLIST parent

	lang CDATA #IMPLIED

>



<!-- B.1.10.7 Relevant medical history and concurrent conditions of parent -->

<!ELEMENT parentmedicalhistoryepisode 

        (parentmdepisodemeddraversion?	,

	parentmedicalepisodename?               ,

        parentmedicalstartdateformat?           ,

	parentmedicalstartdate?                 ,

	parentmedicalcontinue?                  ,

        parentmedicalenddateformat?             ,

	parentmedicalenddate?                   ,

	parentmedicalcomment?)>

<!ATTLIST parentmedicalhistoryepisode

	lang CDATA #IMPLIED

>



<!-- B.1.10.8 Relevant past drug history -->

<!ELEMENT parentpastdrugtherapy 

        (parentdrugname?                  ,

        parentdrugstartdateformat?        ,

	parentdrugstartdate?              ,

        parentdrugenddateformat?          ,

	parentdrugenddate?                ,

	parentdrgindicationmeddraversion? ,

	parentdrugindication?             ,

	parentdrgreactionmeddraversion?   ,

	parentdrugreaction?)>

<!ATTLIST parentpastdrugtherapy

	lang CDATA #IMPLIED

>



<!-- B.2 Reaction(s) / Event(s) -->

<!ELEMENT reaction		

        (primarysourcereaction?         ,

	reactionmeddraversionllt?       ,

    	reactionmeddrallt?		,

    	reactionmeddraversionpt?        ,

    	reactionmeddrapt?           	,

	termhighlighted?                ,

        reactionstartdateformat?        ,

	reactionstartdate?              ,

        reactionenddateformat?          ,

	reactionenddate?                ,

	reactionduration?               ,

        reactiondurationunit?           ,

	reactionfirsttime?              ,

        reactionfirsttimeunit?          ,

	reactionlasttime?               ,

        reactionlasttimeunit?           ,

	reactionoutcome?)>

<!ATTLIST reaction

	lang CDATA #IMPLIED

>



<!-- B.3 Results of tests and procedures relevant to the investigation of the patient: -->

<!ELEMENT test			



        (testdateformat?                ,

        testdate?                       ,

	testname?                       ,

	testresult?                     ,

	testunit?                       ,

	lowtestrange?                   ,

	hightestrange?                  ,

	moreinformation?)>

<!ATTLIST test

	lang CDATA #IMPLIED

>



<!ELEMENT drug			

	(drugcharacterization?          ,

	medicinalproduct?               ,

	obtaindrugcountry?              ,

	drugbatchnumb?                  ,

	drugauthorizationnumb?          ,

	drugauthorizationcountry?       ,

	drugauthorizationholder?        ,

	drugstructuredosagenumb?        ,

	drugstructuredosageunit?        ,

	drugseparatedosagenumb?         ,

	drugintervaldosageunitnumb?     ,

	drugintervaldosagedefinition?   ,

	drugcumulativedosagenumb?       ,

	drugcumulativedosageunit?       ,

	drugdosagetext?                 ,

	drugdosageform?                 ,

	drugadministrationroute?        ,

	drugparadministration?          ,

	reactiongestationperiod?        ,

        reactiongestationperiodunit?    ,

    	drugindicationmeddraversion?	,

	drugindication?                 ,

        drugstartdateformat?            ,

	drugstartdate?                  ,

	drugstartperiod?		,

        drugstartperiodunit?            ,

	druglastperiod?			,

        druglastperiodunit?             ,

        drugenddateformat?              ,

	drugenddate?                    ,

	drugtreatmentduration?          ,

        drugtreatmentdurationunit?      ,

	actiondrug?                     ,

	drugrecurreadministration?      ,

	drugadditional?                 ,

		(activesubstance*               ,

		drugrecurrence*                 ,

		drugreactionrelatedness*))>

<!ATTLIST drug

	lang CDATA #IMPLIED

>



<!ELEMENT activesubstance	     (activesubstancename)>

<!ATTLIST activesubstance

	lang CDATA #IMPLIED

>



<!ELEMENT drugrecurrence               

	(drugrecuractionmeddraversion?    ,

         drugrecuraction)>

<!ATTLIST drugrecurrence

	lang CDATA #IMPLIED

>



<!-- B.4.k.18 Relatedness of drug to reaction / event -->

<!ELEMENT drugreactionrelatedness 

        (drugreactionassesmeddraversion? ,

	drugreactionasses?               ,

	drugassessmentsource?            ,

	drugassessmentmethod?            ,

	drugresult?)>

<!ATTLIST drugreactionrelatedness

	lang CDATA #IMPLIED

>



<!-- B.5 Narrative case summary and further information: -->

<!ELEMENT summary               

	(narrativeincludeclinical?      ,

	reportercomment?                ,

	senderdiagnosismeddraversion?                ,

	senderdiagnosis?                ,

	sendercomment?)>

<!ATTLIST summary

	lang CDATA #IMPLIED

>



<!ELEMENT safetyreportversion		(#PCDATA)>

<!ATTLIST safetyreportversion

	lang CDATA #IMPLIED

>



<!-- A.1.0.1 Sender's(case) Safety Report Unique Identifier -->

<!ELEMENT safetyreportid		(#PCDATA)>

<!ATTLIST safetyreportid

	lang CDATA #IMPLIED

>





<!-- A.1.1 Identification of the country of the primary -->

<!ELEMENT primarysourcecountry       (#PCDATA)>

<!ATTLIST primarysourcecountry

	lang CDATA #IMPLIED

>



<!-- A.1.2 Identification of the country where the reaction / event occurred -->

<!ELEMENT occurcountry               (#PCDATA)>

<!ATTLIST occurcountry

	lang CDATA #IMPLIED

>





<!-- A.1.3a Date of this transmission format -->

<!ELEMENT transmissiondateformat     (#PCDATA)>

<!ATTLIST transmissiondateformat

        lang CDATA #IMPLIED

>



<!-- A.1.3b Date of this transmission -->

<!ELEMENT transmissiondate           (#PCDATA)>

<!ATTLIST transmissiondate

	lang CDATA #IMPLIED

>



<!-- A.1.4 Type of report -->

<!ELEMENT reporttype                 (#PCDATA)>

<!ATTLIST reporttype

	lang CDATA #IMPLIED

>



<!-- A.1.5.1 Serious -->

<!ELEMENT serious                    (#PCDATA)>

<!ATTLIST serious

	lang CDATA #IMPLIED

>



<!-- A.1.5.2 Seriousness criteria -->

<!ELEMENT seriousnessdeath           (#PCDATA)>

<!ATTLIST seriousnessdeath

	lang CDATA #IMPLIED

>

<!ELEMENT seriousnesslifethreatening         (#PCDATA)>

<!ATTLIST seriousnesslifethreatening

	lang CDATA #IMPLIED

>

<!ELEMENT seriousnesshospitalization         (#PCDATA)>

<!ATTLIST seriousnesshospitalization

	lang CDATA #IMPLIED

>

<!ELEMENT seriousnessdisabling       (#PCDATA)>

<!ATTLIST seriousnessdisabling

	lang CDATA #IMPLIED

>

<!ELEMENT seriousnesscongenitalanomali       (#PCDATA)>

<!ATTLIST seriousnesscongenitalanomali

	lang CDATA #IMPLIED

>

<!ELEMENT seriousnessother           (#PCDATA)>

<!ATTLIST seriousnessother

	lang CDATA #IMPLIED

>



<!-- A.1.6a Date report was first received from source format -->

<!ELEMENT receivedateformat          (#PCDATA)>

<!ATTLIST receivedateformat

        lang CDATA #IMPLIED

>



<!-- A.1.6b Date report was first received from source -->

<!ELEMENT receivedate                (#PCDATA)>

<!ATTLIST receivedate

	lang CDATA #IMPLIED

>



<!-- A.1.7a Date of receipt of the most recent information for this report -->

<!ELEMENT receiptdateformat          (#PCDATA)>

<!ATTLIST receiptdateformat

        lang CDATA #IMPLIED

>



<!-- A.1.7b Date of receipt of the most recent information for this report -->

<!ELEMENT receiptdate                (#PCDATA)>

<!ATTLIST receiptdate

	lang CDATA #IMPLIED

>



<!-- A.1.8.1 Are additional documents available -->

<!ELEMENT additionaldocument         (#PCDATA)>

<!ATTLIST additionaldocument

	lang CDATA #IMPLIED

>



<!-- A.1.8.2 List of documents held by sender -->

<!ELEMENT documentlist               (#PCDATA)>

<!ATTLIST documentlist

	lang CDATA #IMPLIED

>



<!-- A.1.9 Does this case fulfill the local criteria for an expedited report -->

<!ELEMENT fulfillexpeditecriteria    (#PCDATA)>

<!ATTLIST fulfillexpeditecriteria

	lang CDATA #IMPLIED

>



<!--

The A.1.10 - The worldwide unique case identification number must be populated as per the following user guidance:



Only A.1.10.1 or A.1.10.2 should be used.  No case should ever have more than one of these items completed.  The contents of whichever item is used should remain unchanged for any transmissions subsequent to the original transmission. When a regulator is the initial sender A.1.10.1 should be used. When an entity other than a regulator is the initial sender, A.1.10.2 should be used. When a sender has not previously received a valid E2B/M2 report electronically, the identifiers (content and format) in A.1.0.1 and A.1.10.1 or A.1.10.2 should be identical.  Retransmitters should use their own sender's (case) safety report unique identifier (A.1.0.1), but not change A.1.10.1 or A.1.10.2. Examples are available in attachment 3 of the E2BM document.

 The contents of the fields A.1.10.1 and/or A.1.10.2 should first list A.1.1 - Identification of the country of primary source and secondly list A.3.1.2 - Sender Identifier, Sender Organization, and lastly, the company international case report number, delimited by hyphens.



For example, a report transmitted by a US company to a regulatory authority would populate A.1.10.2 with "US-Company Name-12345", where "12345" is the company's unique case report number.  In the event that the regulatory authority transmitted this ICSR to another regulatory authority, A.1.10.2 would remain the same.  The regulatory authority would not populate A.1.10.1.



If the situation occurs where multiple reports are received about the same case, such as a report from a physician and a report from another company, the information may be merged.  One number will be maintained as the case number in its original field and the second number will be listed as a suspected duplicate. 

-->

<!-- A.1.10.1 Regulatory authority's case report number -->

<!ELEMENT authoritynumb              (#PCDATA)>

<!ATTLIST authoritynumb

	lang CDATA #IMPLIED

>



<!-- A.1.10.2 Other sender's case report number -->

<!ELEMENT companynumb                (#PCDATA)>

<!ATTLIST companynumb

	lang CDATA #IMPLIED

>



<!-- A.1.11 Other case identifiers in previous transmissions -->

<!ELEMENT duplicate                  (#PCDATA)>

<!ATTLIST duplicate

	lang CDATA #IMPLIED

>



<!-- A.1.11.1 Source(s) of the case identifier -->

<!ELEMENT duplicatesource            (#PCDATA)>

<!ATTLIST duplicatesource

	lang CDATA #IMPLIED

>



<!-- A.1.11.2 Case identifier(s) -->

<!ELEMENT duplicatenumb              (#PCDATA)>

<!ATTLIST duplicatenumb

	lang CDATA #IMPLIED

>



<!-- A.1.12 Identification number of the report which is linked to this report -->

<!ELEMENT linkreportnumb             (#PCDATA)>

<!ATTLIST linkreportnumb

	lang CDATA #IMPLIED

>



<!-- A.1.13 Report nullification -->

<!ELEMENT casenullification          (#PCDATA)>

<!ATTLIST casenullification

	lang CDATA #IMPLIED

>



<!-- A.1.13.1 Reason for nullification -->

<!ELEMENT nullificationreason        (#PCDATA)>

<!ATTLIST nullificationreason

	lang CDATA #IMPLIED

>



<!-- A.1.14 Was the case medically confirmed, if not initially from health professional? -->

<!ELEMENT medicallyconfirm           (#PCDATA)>

<!ATTLIST medicallyconfirm

	lang CDATA #IMPLIED

>



<!-- A.2.1.1a Reporter identifier -->

<!ELEMENT reportertitle              (#PCDATA)>

<!ATTLIST reportertitle

	lang CDATA #IMPLIED

>



<!-- A.2.1.1b Reporter identifier -->

<!ELEMENT reportergivename           (#PCDATA)>

<!ATTLIST reportergivename

	lang CDATA #IMPLIED

>



<!-- A.2.1.1c Reporter identifier -->

<!ELEMENT reportermiddlename         (#PCDATA)>

<!ATTLIST reportermiddlename

	lang CDATA #IMPLIED

>



<!-- A.2.1.1d Reporter identifier -->

<!ELEMENT reporterfamilyname         (#PCDATA)>

<!ATTLIST reporterfamilyname

	lang CDATA #IMPLIED

>



<!-- A.2.1.2a Reporter's address -->

<!ELEMENT reporterorganization       (#PCDATA)>

<!ATTLIST reporterorganization

	lang CDATA #IMPLIED

>



<!-- A.2.1.2b Reporter's address -->

<!ELEMENT reporterdepartment         (#PCDATA)>

<!ATTLIST reporterdepartment

	lang CDATA #IMPLIED

>



<!-- A.2.1.2c Reporter's address -->

<!ELEMENT reporterstreet             (#PCDATA)>

<!ATTLIST reporterstreet

	lang CDATA #IMPLIED

>



<!-- A.2.1.2d Reporter's address -->

<!ELEMENT reportercity               (#PCDATA)>

<!ATTLIST reportercity

	lang CDATA #IMPLIED

>



<!-- A.2.1.2e Reporter's address -->

<!ELEMENT reporterstate              (#PCDATA)>

<!ATTLIST reporterstate

	lang CDATA #IMPLIED

>



<!-- A.2.1.2f Reporter's address -->

<!ELEMENT reporterpostcode           (#PCDATA)>

<!ATTLIST reporterpostcode

	lang CDATA #IMPLIED

>



<!-- A.2.1.3 Country -->

<!ELEMENT reportercountry            (#PCDATA)>

<!ATTLIST reportercountry

	lang CDATA #IMPLIED

>



<!-- A.2.1.4 Qualification -->

<!ELEMENT qualification              (#PCDATA)>

<!ATTLIST qualification

	lang CDATA #IMPLIED

>



<!-- A.2.2 Literature reference(s) -->

<!ELEMENT literaturereference        (#PCDATA)>

<!ATTLIST literaturereference

	lang CDATA #IMPLIED

>



<!-- A.2.3.1 Study name -->

<!ELEMENT studyname                  (#PCDATA)>

<!ATTLIST studyname

	lang CDATA #IMPLIED

>



<!-- A.2.3.2 Sponsor study number -->

<!ELEMENT sponsorstudynumb           (#PCDATA)>

<!ATTLIST sponsorstudynumb

	lang CDATA #IMPLIED

>



<!-- A.2.3.3 Study type in which the reactions / events were observed -->

<!ELEMENT observestudytype           (#PCDATA)>

<!ATTLIST observestudytype

	lang CDATA #IMPLIED

>



<!-- A.3.1.1 Sender type -->

<!ELEMENT sendertype                 (#PCDATA)>

<!ATTLIST sendertype

	lang CDATA #IMPLIED

>



<!-- A.3.1.2 Sender organization -->

<!ELEMENT senderorganization         (#PCDATA)>

<!ATTLIST senderorganization

	lang CDATA #IMPLIED

>



<!-- A.3.1.3a Person responsible for sending the report -->

<!ELEMENT senderdepartment           (#PCDATA)>

<!ATTLIST senderdepartment

	lang CDATA #IMPLIED

>



<!-- A.3.1.3b Person responsible for sending the report -->

<!ELEMENT sendertitle                (#PCDATA)>

<!ATTLIST sendertitle

	lang CDATA #IMPLIED

>



<!-- A.3.1.3c Person responsible for sending the report -->

<!ELEMENT sendergivename             (#PCDATA)>

<!ATTLIST sendergivename

	lang CDATA #IMPLIED

>



<!-- A.3.1.3d Person responsible for sending the report -->

<!ELEMENT sendermiddlename           (#PCDATA)>
